import { ACCOUNT_TYPES, ACCOUNT_TYPE_VALUES } from './accountTypes.js';

export const REGISTRATION_QUESTIONNAIRE_TARGETS = {
  AFFILIATE: ACCOUNT_TYPES.AFFILIATE,
  ADVERTISER: ACCOUNT_TYPES.ADVERTISER,
};

export const REGISTRATION_QUESTIONNAIRE_TARGET_VALUES = ACCOUNT_TYPE_VALUES;

export const QUESTIONNAIRE_FIELD_TYPES = {
  TEXT: 'text',
  TEXTAREA: 'textarea',
  SELECT: 'select',
  MULTISELECT: 'multiselect',
  CHECKBOX: 'checkbox',
  RADIO: 'radio',
};

export const QUESTIONNAIRE_FIELD_TYPE_VALUES = Object.values(
  QUESTIONNAIRE_FIELD_TYPES,
);

export const QUESTIONNAIRE_OPTION_FIELD_TYPES = new Set([
  QUESTIONNAIRE_FIELD_TYPES.SELECT,
  QUESTIONNAIRE_FIELD_TYPES.MULTISELECT,
  QUESTIONNAIRE_FIELD_TYPES.RADIO,
]);

export const QUESTIONNAIRE_BLOCKED_ROUTES = new Set([
  REGISTRATION_QUESTIONNAIRE_TARGETS.AFFILIATE,
  REGISTRATION_QUESTIONNAIRE_TARGETS.ADVERTISER,
]);
